import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import requestVideos from "../utils/requests";

export default function Home() {
  const [video, setVideo] = useState(0);

  useEffect(() => {
    pegandoVideo();
  });

  async function pegandoVideo() {
    const response = await requestVideos("Cats", 1);
    return setVideo(response.videos[0].video_files[1].link);
  }
  return (
    <>
      <Head>
        <title>Player</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <video src={video} controls />
        </div>
      </main>
    </>
  );
}
